language: node_js
node_js:
  - '6'
dist: trusty
sudo: false
addons:
  chrome: stable
  firefox: '59.0'
  browserstack:
    username: "jrmemacias1"
    access_key:
      secure: "XktU+Qw6ZfSiiJGhMxo6g5bjhaCReXdrkqrgTCRyqy2FCYsVsSc38JFXiIrpzuOHsHKamY4WvHPHPli+9ll6+WbZC8YtgR7MZj8itEO/vfJrue/0+UTAyCuaRSBxaY9b0NEOnlSGf1I4fXNhAXMK6hBJgg1XghPXwAOXghirlO/HFT31ta3Ha/Kktjrj/KQl19QxknSrXzPAXLOacAVd7lbARbkP3FNyx3gCR5+8c2uU0TyDWcw9I5RxhEvnkgNarH/V/whDC09I2hyM5JauqsakLwphRCu9jzFoxn+l7pMJwXqN+YcJ+IUH3DZDiuWfVBx+yGk399CV9ovlOeXYAY8OTNkoptxM0Sbk3AymIhDb+SZ9kR8htiZFZdVP0cp4uHaNL7AYPfKvFREWCkoG6gd6vXSep70rWvibmsHeoPAKpdUkB9eBe2HiTeDKZUveC1IZhg07pDXcZ13e1w0IbjmOxQRWU7r8+Wo1tyikmFNFgQpwJZfxe+iNptMQwaJGBA+SuU4lyDT/GYx8UiL15LU1umq/SL6fzbFwpXLuygXRvoCuNOzWnZawLhFzVtGYqaNtm57fV/2iIs1yR8DRp3MAhPOS+dx3jJNf2qh5FBMri7SpfdXEie+hoJfa//eWNjeErATTzbs6AJ+6+EP0wtmLp2Hr48HmzAfncMHapW0="
  sauce_connect:
    username: jeromemacias-nodium
  jwt:
    secure: "V7IR2EMmqYzaOnD5rZ3nXaKNijFSgqSE7+9Ekuwbc4e009X2ixO6jGHQVwd+JzxsHjGfY9jrz6Y3r90LFzTxYfCUgxoxCPrTn4AWRUtEKLWe2XIBOVzCDPSkugS1yM5rtjYbu+DxcRAamLo2Bi4VZNcO12PHWsqgmOYCkx+vreNGFsJzKM7Kpq5Ke3DnlP4clwf49guSgnoNPTqdyrK3cxaEJlBACvQ7sJHWF3YVmbHOwPwd3Z4YL6L70gs1I/XN32h2oscVzLRaGQ69Dpkw61oZVL8IKAxS3NEWLAratt3KzIrdhKzUTZzUeuJY+mKRupziQqPTReedhCcQZ2eJjF1Hzw0GDK0QjR2s5KOSGOo8ihAKd6d3u6lcW17gtTvl0c/ZzbEu8UAnLJTlX8AKqTcbz2+hW6VKqVtgIgNyc47OESRbfaR2ZKy1KlqmGxUgg0JT00U1vcvi6I6HgZ1yOIDVWg32yOsZdluStZyFZG2X6Mh2ZQL8qAhiDfWTvR4opTKc6Yc5AOPDZbsIWLzOg5DcFFvrKcNPJO4hM21ksgN7nXUqvoCa3DGT7YBY1Z42VPvEI9dDvHzPeLa3lJSwjAR11NCHmS7Zn7ucfugtH9Rfj7WCz/EH4tpk0FsmmSfS6jG2zQoZ/SyDQgWm+NdB4LI8OWZ6Z60wHETbuHvzP7Q="
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - SELENIUM_BROWSER=chrome SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/chromedriver_2.26
    - SELENIUM_BROWSER=firefox SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/geckodriver-v0.11.1
    - BROWSERSTACK=true SELENIUM_BROWSER=chrome
    - BROWSERSTACK=true SELENIUM_BROWSER=firefox
    - SAUCE=true SELENIUM_BROWSER=chrome
    - SAUCE=true SELENIUM_BROWSER=firefox
cache:
  directories:
    - node_modules
install:
  - make install
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - make test-local
branches:
  only:
    - master
