language: node_js
node_js:
    - '6'
dist: trusty
sudo: false
addons:
    chrome: stable
    firefox: latest
    browserstack:
        username: 'jrmemacias1'
        access_key:
            secure: 'iC/Jx7XUeVT3fkDAwY0Ks9IrCX4jTlxc/hfDslvpm4/XILa1oneFjg7vzy2dbaEsOTeYPD1MDOc+EHn4BPuMj/++PcmgaVQmRkzfm8EZ1aNANDuLWWt3iI4KqullSIlrAg3qAM3AFEwxnj3CC9GvK2DziK8BPiJs/DlrEyjys4Kx3LRAE+q75PDdfv7/Wiyaq94/RjXpt6n6phYtPsAeGEe/J20r4DOg43FtJ9D33xSZsHrmJJ8psBRHFEC8PYh+YuxKJpHzh40FvGGgiq2NGP//bXwoOcp5aR5cj1+Axp7EaGkkmsAsQqCilCJZr7UXl9m7A0OSJlm5M73WaVZ9JbK6x4xpveWMIAqXW67gxLZW8Dpd6jsrqjNZzpbV937coeqT0cf6eddzvfpRkqEouWMo/PVE9apBBe0bGQREq29iREMvobij1DPOOt5smiu1GZEmm4q1JnnHTcWOzyphYct7QRqK7j1FIkF+g2j/KWrI555gOTCe8/DRcTfeQJ2yWCOCg4VssmkN2O+bR3g8HPjtx+F1kA0dMhE/y/Gw+tjYvEfdT2r7AI1YEtzIcJUNUDVPa36ROeJpO7zPG/jyJW7U7Q/mvCAzs0HLRv4BMnWWjKxF9IKVTYbRFiIwVZcyoqJSXs+VhyXQI/FT0Egr5WtJcaxiNp4CTvMv0FjdEYY='
    sauce_connect:
        username: jeromemacias-nodium
env:
    global:
        - DISPLAY=:99.0
    matrix:
        - SELENIUM_BROWSER=chrome SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/chromedriver_2.42
        - SELENIUM_BROWSER=firefox SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/geckodriver-v0.22.0
        - BROWSERSTACK=true SELENIUM_BROWSER=chrome
        - BROWSERSTACK=true SELENIUM_BROWSER=firefox
        - SAUCE=true SELENIUM_BROWSER=chrome
        - SAUCE=true SELENIUM_BROWSER=firefox
cache:
    directories:
        - node_modules
install:
    - make install
before_script:
    - sh -e /etc/init.d/xvfb start
script:
    - make test-local
branches:
    only:
        - master
