language: node_js
node_js:
  - '6'
dist: trusty
sudo: false
addons:
  chrome: stable
  firefox: '59.0'
  browserstack:
    username: "jrmemacias1"
    access_key:
      secure: "hdAnQQ5QkBDsbT2fVkterMYG3kxt8Z/4elyuMshNUifNPdm6nkCNfH6hQgfEqmiUjgkaedePKqBZphZ0wmXg0mrO0VTIJ8vE1tzwM3fwwWCdRSCp1Dh5lQt04UC9pENt+e21NQhNly+oLQKFCTONNcKlU4uQUPXcdjqY+16BGyY4l510R0xHGQfEFhMFiIiay90tErUgefPFi/eU49mhfMNsIeeIB23avgsZZ6a1528p3R+2Wz4RuNCkwvhCFzbJRrkG/luNYMFNzglyZjzTBv05giPeaYwbq1UqqHi2wbuWXua6KhCLv6BlGxYOroFNNhzQNf9d455NpYt41imwthOuqsJzeG+W6GW2YpuCh7XYHVe/aDj/0tqHch0BQWN6B7ky+gP5+FCnJCZe+W2vaMsIn4FyyJnJm6y6qE5X+2r4zFptTeAqM1NaWusmPYKzLXYLBji1VC0Angv6X8koFhEIZmyIdO7o+H2oesXdJM1vQXvUH+5FPtftjC6EYENR3Za392j2oYTvSn4z2v7X6X3xmzwzzY9nttbCZ2uYQrjpBmPDkbTX6SXzpyxtgZZ9WvF249FE2FgTnaaHsLoAmvTNhrPYYrlUw3vGt3ICLrBSroOyN7/PRybO/k/ao3y+x8soqunpPi9NlU34WBsWZkkcY2HWgJFqMGqmWxx9F94="
  sauce_connect:
    username: jeromemacias-nodium
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - SELENIUM_BROWSER=chrome SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/chromedriver_2.36
    - SELENIUM_BROWSER=firefox SELENIUM_BROWSER_BINARY_PATH=node_modules/webdriver-manager/selenium/geckodriver-v0.20.0
    - BROWSERSTACK=true SELENIUM_BROWSER=chrome
    - BROWSERSTACK=true SELENIUM_BROWSER=firefox
    - SAUCE=true SELENIUM_BROWSER=chrome
    - SAUCE=true SELENIUM_BROWSER=firefox
cache:
  directories:
    - node_modules
install:
  - make install
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - make test-local
branches:
  only:
    - master
